server:
  port: 8082
spring:
  application:
    name: zk-client2
  cloud:
    zookeeper:
      connect-string: localhost:2181
      dependencies:
        zk-client1-alias: # 别名
          required: true # zk中在path中未找到服务时，本项目启动会报错
          path: /zk-client1
